# Generated by Django 5.2.4 on 2025-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
