# Generated by Django 5.2.4 on 2025-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_alter_checkout_checkout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
