# Generated by Django 5.2.4 on 2025-08-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_checkout_checkout_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStocks',
            fields=[
                ('instocks_id', models.AutoField(primary_key=True, serialize=False)),
                ('incoming_stocks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.stocks')),
            ],
        ),
    ]
