# Generated by Django 5.2.4 on 2025-07-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stocks_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.CharField(max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.supplier')),
            ],
        ),
    ]
