# Generated by Django 5.2.4 on 2025-08-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_instocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingStocks',
            fields=[
                ('IncomingStocks_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='InStocks',
        ),
    ]
