# Generated by Django 5.2.4 on 2025-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_incomingstocks_delete_instocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingstocks',
            name='incoming_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingstocks',
            name='incoming_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
