# Generated by Django 5.2.4 on 2025-09-01 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0006_incomingstocks_incoming_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,15}', 'Enter 11 digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter mobile number')]),
        ),
    ]
