# Generated by Django 5.2.4 on 2025-07-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0006_remove_product_supplier_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='mit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
