# Generated by Django 5.2.4 on 2025-07-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0007_stocks_mit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='mit',
            new_name='limit',
        ),
    ]
