# Generated by Django 5.2.4 on 2025-09-03 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0007_alter_customer_number_alter_supplier_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}', 'Enter 11 digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter mobile number')]),
        ),
    ]
