# Generated by Django 5.2.4 on 2025-07-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0008_rename_mit_stocks_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='percentage',
            new_name='actual_count',
        ),
    ]
