# Generated by Django 5.2.4 on 2025-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0009_rename_percentage_stocks_actual_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='actual_count',
            field=models.IntegerField(max_length=100),
        ),
    ]
