# Generated by Django 5.2.4 on 2025-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0010_alter_stocks_actual_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='actual_count',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='limit',
        ),
        migrations.AddField(
            model_name='stocks',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
