# Generated by Django 5.2.4 on 2025-07-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0011_remove_stocks_actual_count_remove_stocks_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='percentage',
        ),
    ]
