# Generated by Django 5.2.4 on 2025-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0012_remove_stocks_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
