# Generated by Django 5.2.4 on 2025-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0013_stocks_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='percentage',
        ),
        migrations.AddField(
            model_name='stocks',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
