# Generated by Django 5.2.4 on 2025-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0014_remove_stocks_percentage_stocks_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='limit',
            new_name='actual_count',
        ),
    ]
