# Generated by Django 5.2.4 on 2025-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0015_rename_limit_stocks_actual_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
