# Generated by Django 5.2.4 on 2025-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0016_product_product_image_product_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
