# Generated by Django 5.2.4 on 2025-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0017_alter_product_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
