# Generated by Django 5.2.4 on 2025-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0018_alter_product_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
