# Generated by Django 5.2.4 on 2025-07-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0019_stocks_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sum_per_transaction',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
