# Generated by Django 5.2.4 on 2025-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0020_product_sum_per_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sum_per_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
