# Generated by Django 5.2.4 on 2025-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0022_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
