# Generated by Django 5.2.4 on 2025-07-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0024_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='count_per_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
