# Generated by Django 5.2.4 on 2025-07-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0025_stocks_count_per_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='count_per_product',
        ),
    ]
