# Generated by Django 5.2.4 on 2025-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0026_remove_stocks_count_per_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
