# Generated by Django 5.2.4 on 2025-07-23 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0027_alter_stocks_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('product_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.productname'),
        ),
    ]
