# Generated by Django 5.2.4 on 2025-08-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0028_productname_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.customer')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.productname')),
                ('product_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
            ],
        ),
    ]
